### ISSUE TITLE
How about the performance compare with SC using 360 deg mechanical LiDAR?

### ISSUE THREAD

**Issue by qpc001** [sparolab/solid#1]

**Comment by hogyun2** [comment]
It was confirmed that **SOLID** outperformed SC in KITTI 00, but it is the opposite in KITTI 02.
In other words, the performance of the two methods is similar at 360-degree mechanical LiDAR.
However, regarding weight-to-weight performance, our method performs about four times better than SC, and SOLiD can handle problems from different angles.
