### ISSUE TITLE
Adaptness for helmet-mounted LiDAR scenarios

### ISSUE THREAD

**Issue by zhh2005757** [sparolab/solid#2]
Hi author, thanks for opening such great work! Since the pedestrain will wag his head during traveling, I wonder if this method can be used for helmet-mounted LiDAR worn by pedestrains?

**Comment by hogyun2** [comment]
I appreciate your interest in our paper!

I think it would be possible if the helmet-mounted LiDAR you said meant an Outster or Livox LiDAR!
